services:
  - type: web
    name: telegram-financial-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free